return of docker

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,4 +1,4 @@
-# "merge_request" workflow (https://docs.gitlab.com/ee/ci/yaml/workflow.html)
+# Using "merge_request into main" workflow (https://docs.gitlab.com/ee/ci/yaml/workflow.html)
 include:
   - template: "Workflows/MergeRequest-Pipelines.gitlab-ci.yml"
 
@@ -7,22 +7,16 @@ stages:
   - test
   - deploy
 
-default:
-  image: registry.gitlab.com/sosiristseng/docker-juliabook:latest
-
-variables:
-  JULIA_DEPOT_PATH: "$CI_PROJECT_DIR/.julia"
-
 # GitLab CI: Auto dependency updates https://thacoon.com/posts/gitlab-ci-auto-dependency-update/
 # `GIT_PUSH_TOKEN` CI/CD variable = personal access token (PAT) with write access
 update-julia:
-  # tags:
-  #   - md705
+  image: julia:1.7
   rules:
     - if: $CI_PIPELINE_SOURCE == "schedule"
   variables:
     JULIA_PKG_PRECOMPILE_AUTO: 0
   script:
+    - apt-get update && apt-get install -y --no-install-recommends git
     - julia --color=yes --threads=auto --project=@. -e 'import Pkg; Pkg.update()'
     # Open a MR when there is a update, requires GIT_PUSH_TOKEN` CI/CD variable = personal access token (PAT) with write access
     - |
@@ -47,12 +41,63 @@ update-julia:
         echo "no change, nothing to commit"
       fi
 
-build-notebooks:
-  tags:
-    - md705
+# Taken from https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/
+# Build docker images and tag it by git SHA
+build-docker:
+  image: docker:20.10
+  services:
+    - docker:20.10-dind
+  stage: build
+  rules:
+    - if: $CI_PIPELINE_SOURCE != "schedule"
+  script:
+    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
+    - docker pull $CI_REGISTRY_IMAGE:latest || true
+    - >
+      docker build
+      --pull
+      --cache-from $CI_REGISTRY_IMAGE:latest
+      --label "org.opencontainers.image.title=$CI_PROJECT_TITLE"
+      --label "org.opencontainers.image.url=$CI_PROJECT_URL"
+      --label "org.opencontainers.image.created=$CI_JOB_STARTED_AT"
+      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
+      --label "org.opencontainers.image.version=$CI_COMMIT_REF_NAME"
+      --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
+      -f docker/Dockerfile
+      .
+    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
+
+# Default: main = latest
+push-docker:
+  image: docker:20.10
+  services:
+    - docker:20.10-dind
   stage: test
   rules:
-    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
+  variables:
+    GIT_STRATEGY: none
+    TAG: "latest"
+  script:
+    - echo -n $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
+    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
+    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$TAG
+    - docker push $CI_REGISTRY_IMAGE:$TAG
+
+push-tag-docker:
+  extends: push-docker
+  rules:
+    - if: $CI_COMMIT_TAG
+  variables:
+    TAG: $CI_COMMIT_TAG
+
+build-notebooks:
+  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
+  # tags:
+  #   - your_runner
+  stage: test
+  rules:
+    - if: $CI_PIPELINE_SOURCE != "schedule"
   cache:
     - key:
         files:
@@ -60,33 +105,24 @@ build-notebooks:
           - requirements.txt
         prefix: jb
       paths:
-        - docs/_build/.jupyter_cache
-    - key:
-        files:
-          - Project.toml
-          - Manifest.toml
-        prefix: julia-1.7
-      paths:
-        - $CI_PROJECT_DIR/.julia/
+        - docs/_build/
   before_script:
-    - julia --color=yes --threads=auto -e 'import Pkg; Pkg.add("IJulia"); Pkg.build("IJulia")'
-    - julia --color=yes --threads=auto --project=@. -e 'import Pkg; Pkg.instantiate(); Pkg.resolve(); Pkg.precompile()'
-    - jb build docs --warningiserror --keep-going
+    # Uncomment if you want parallel notebook execution
+    # - find docs -type f -name "*.ipynb" -print0 | parallel -0 -j2 jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --ExecutePreprocessor.kernel_name=julia-1.7 --execute --inplace {}
+    - jupyter-book build docs
   script:
-    - echo "Test complete!"
+    - "Test build completed."
   artifacts:
     paths:
       - docs/_build/
-    expire_in: 1 week
 
 pages:
   extends: build-notebooks
-  stage: deploy
   rules:
     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
   script:
     - mv docs/_build/html public
-    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip -f -k {} \; -exec brotli -f -k {} \; || echo 'Compression failed. Skipping...'
+    # - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|svg\|xml\)$' -exec gzip -f -k {} \; -exec  -f -k {} \; || echo 'Compression failed. Skipping...'
   artifacts:
     paths:
       - public
