parallel matrix

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: CI
+name: CI with dynamic parallel matrix
 
 on:
   workflow_dispatch:
@@ -12,104 +12,164 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  LITERATE_PROC: '2'
   JULIA_CI: 'true'
-  PY_VER: '3.14'
   JULIA_CONDAPKG_BACKEND: 'Null'
-  JULIA_NUM_THREADS: '2'
+  JULIA_NUM_THREADS: 'auto'
   OPENBLAS_NUM_THREADS: '1'
   NBCACHE: '.cache'
+  PY_VER: '3.14'
 
 jobs:
-  CI:
+  setup:
     runs-on: ubuntu-latest
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+      hash: ${{ steps.hash.outputs.value }}
+      ver: ${{ steps.julia-version.outputs.resolved }}
     steps:
     - name: Checkout repository
       uses: actions/checkout@v6
     - name: Setup Python
       uses: actions/setup-python@v6
+      id: setup-python
       with:
         python-version: ${{ env.PY_VER }}
-        cache: 'pip'
     - name: Read Julia version
       id: julia-version
-      uses: julia-actions/julia-version@main
-      with:
-        versions: manifest
-    - name: Get hashes
+      run: python -c 'import tomllib; from pathlib import Path; print("resolved=", tomllib.loads(Path("Manifest.toml").read_text())["julia_version"], sep="")' >> "$GITHUB_OUTPUT"
+    - name: Get environment hash
       id: hash
       run: |
         echo "value=${{ hashFiles('Project.toml', 'Manifest.toml', 'src/**') }}" >> "$GITHUB_OUTPUT"
-        echo "nb=${{ hashFiles('docs/**/*.jl', 'docs/**/*.ipynb') }}" >> "$GITHUB_OUTPUT"
-    - name: Cache executed notebooks
+        echo "ver=${{ runner.os }}-julia-${{ steps.julia-version.outputs.resolved }}" >> "$GITHUB_OUTPUT"
+    - name: Cache Julia packages
       uses: actions/cache@v5
-      id: cache-nb
-      with:
-        path: |
-          ${{ env.NBCACHE }}/**/*.ipynb
-          ${{ env.NBCACHE }}/**/*.sha
-        key: notebook-${{ steps.hash.outputs.value }}-${{ steps.hash.outputs.nb }}
-        restore-keys: |
-          notebook-${{ steps.hash.outputs.value }}-
-    - name: Setup Julia
-      uses: julia-actions/setup-julia@v2
-      if: ${{ steps.cache-nb.outputs.cache-hit != 'true' }}
-      with:
-        version: ${{ steps.julia-version.outputs.resolved }}
-    - name: Restore Julia packages
-      uses: actions/cache/restore@v5
-      if: ${{ steps.cache-nb.outputs.cache-hit != 'true' && runner.environment == 'github-hosted'}}
       id: cache-julia
       with:
         path: ~/.julia
-        key: ${{ runner.os }}-julia-${{ steps.julia-version.outputs.resolved }}-${{ steps.hash.outputs.value }}
+        key: ${{ steps.hash.outputs.ver }}-${{ steps.hash.outputs.value }}
         restore-keys: |
-          ${{ runner.os }}-julia-${{ steps.julia-version.outputs.resolved }}-
+          ${{ steps.hash.outputs.ver }}-
+    - name: Setup Julia
+      uses: julia-actions/setup-julia@v2
+      if: ${{ steps.cache-julia.outputs.cache-hit != 'true' }}
+      with:
+        version: ${{ steps.julia-version.outputs.resolved }}
     - name: Install Julia packages
-      if: ${{ steps.cache-nb.outputs.cache-hit != 'true' && (runner.environment == 'self-hosted' || steps.cache-julia.outputs.cache-hit != 'true') }}
+      if: ${{ steps.cache-julia.outputs.cache-hit != 'true' }}
       shell: julia --color=yes --project=@. {0}
       run: |
         using Pkg, Dates
         Pkg.Registry.update()
         Pkg.instantiate()
+        Pkg.resolve()
         Pkg.precompile()
-        if ENV["RUNNER_ENVIRONMENT"] == "github-hosted"
-            Pkg.gc(;collect_delay=Day(0))
-        end
-    - name: Save Julia packages
-      uses: actions/cache/save@v5
-      if: ${{ steps.cache-nb.outputs.cache-hit != 'true' && runner.environment == 'github-hosted' && steps.cache-julia.outputs.cache-hit != 'true' }}
-      with:
-        path: ~/.julia
-        key: ${{ steps.cache-julia.outputs.cache-primary-key }}
-    - name: Run notebooks
-      if: ${{ steps.cache-nb.outputs.cache-hit != 'true' }}
-      run: |
-        pip install -r requirements.txt
-        julia --project=@. --color=yes -p ${{ env.LITERATE_PROC }} .github/ci.jl
-    - name: Copy back built notebooks
-      run: cp --verbose -rf ${{ env.NBCACHE }}/docs/* docs/
-    - name: Setup NodeJS
-      uses: actions/setup-node@v6
-      with:
-        node-version: 'lts/*'
-    - name: Build website
-      env:
-        BASE_URL: /${{ github.event.repository.name }}
-      working-directory: docs
-      run: |
-        npm install -g "jupyter-book"
-        jupyter-book build --html
-    - name: Upload pages artifact
-      if: ${{ github.ref == 'refs/heads/main' }}
-      uses: actions/upload-pages-artifact@v4
-      with:
-        path: 'docs/_build/html'
+    - name: List notebooks as a JSON array
+      id: set-matrix
+      run: echo "matrix=$(python -c 'import glob, json; print(json.dumps(glob.glob("**/*.ipynb", root_dir="docs", recursive=True) + glob.glob("**/*.jl", root_dir="docs", recursive=True)))')" >> "$GITHUB_OUTPUT"
+
+  execute:
+    needs: setup
+    strategy:
+      max-parallel: 10
+      fail-fast: false
+      matrix:
+        notebook: ${{ fromJSON(needs.setup.outputs.matrix) }}
+    runs-on: ubuntu-latest
+    env:
+      NB: docs/${{ matrix.notebook }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+      - name: Cache notebook
+        uses: actions/cache@v5
+        id: nb-cache
+        with:
+          path: ${{ env.NBCACHE }}
+          key: notebook-${{ needs.setup.outputs.hash }}-${{ hashFiles(env.NB) }}
+      - name: Setup Python
+        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
+        uses: actions/setup-python@v6
+        id: setup-python
+        with:
+          python-version: ${{ env.PY_VER }}
+          cache: 'pip'
+      - name: Setup Julia
+        uses: julia-actions/setup-julia@v2
+        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
+        with:
+          version: ${{ needs.setup.outputs.ver }}
+      - name: Restore Julia packages
+        uses: actions/cache/restore@v5
+        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
+        with:
+          path: ~/.julia
+          key: ${{ runner.os }}-julia-${{ needs.setup.outputs.ver }}-${{ needs.setup.outputs.hash }}
+      - name: Execute notebook
+        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
+        run: |
+          pip install -r requirements.txt
+          julia --project=@. .github/ci.jl
+      - name: Convert artifact Name
+        id: art
+        run: echo "name=$(echo ${{ env.NB }} | sed 's/\//-/g')" >> "$GITHUB_OUTPUT"
+      - name: Upload Notebook
+        uses: actions/upload-artifact@v7
+        with:
+          name: notebook-${{ steps.art.outputs.name }}-${{ needs.setup.outputs.hash }}-${{ hashFiles(env.NB) }}
+          path: ${{ env.NBCACHE }}
+          include-hidden-files: true
+
+  render:
+    needs: execute
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+      - name: Download notebooks
+        uses: actions/download-artifact@v8
+        with:
+          path: ${{ env.NBCACHE }}/
+          pattern: notebook-*
+          merge-multiple: true
+      - name: Copy back built notebooks
+        run: cp --verbose -rf ${{ env.NBCACHE }}/docs/* docs/
+      - name: Setup NodeJS
+        uses: actions/setup-node@v6
+        with:
+          node-version: 'lts/*'
+      - name: Build website
+        env:
+          BASE_URL: /${{ github.event.repository.name }}
+        working-directory: docs
+        run: |
+          npm install -g "jupyter-book"
+          jupyter-book build --html
+      - name: Upload pages artifact
+        if: ${{ github.ref == 'refs/heads/main' }}
+        uses: actions/upload-pages-artifact@v4
+        with:
+          path: 'docs/_build/html'
+
+  # CI conclusion for GitHub status check
+  CI:
+    needs: render
+    if: always()
+    runs-on: ubuntu-slim
+    steps:
+      - run: |
+          if [[ ${{ needs.render.result }} == "success" ]]; then
+            echo "Tests passed"
+            exit 0
+          else
+            echo "Tests failed"
+            exit 1
+          fi
 
   # Deployment job
   deploy:
-    name: Deploy to GitHub pages and Notebook branch
-    needs: CI
+    name: Deploy to GitHub pages
+    needs: render
     if: ${{ github.ref == 'refs/heads/main' }}
     # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
     permissions:
